const reward = {
  dingo: '딩고 호박',
  blackDye: '블랙 염색약',
  increaseWood: '인크리스 우드',
  increaseFire: '인크리스 파이어',
  lightSkillBook1: '빛 스킬북 I',
  lightSkillBook2: '빛 스킬북 II',
  lightSkillBook3: '빛 스킬북 III',
  darkSkillBook1: '어둠 스킬북 I',
  darkSkillBook2: '어둠 스킬북 II',
  darkSkillBook3: '어둠 스킬북 III',
  fireSkillBook1: '불 스킬북 I',
  fireSkillBook2: '불 스킬북 II',
  fireSkillBook3: '불 스킬북 III',
  waterSkillBook1: '물 스킬북 I',
  waterSkillBook2: '물 스킬북 II',
  waterSkillBook3: '물 스킬북 III',
  treeSkillBook1: '나무 스킬북 I',
  treeSkillBook2: '나무 스킬북 II',
  treeSkillBook3: '나무 스킬북 III',
  throneSkillBook: '왕성 스킬북 상자',
  darkMagicCrystal100: '흑마법 결정 100개',
  blackRidingDye: '블랙 탈 것 염색약',
  ivoryRidingDye: '아이보리 탈 것 염색약',
  defensiveKingdom: '디펜시브 킹덤',
  offensiveKingdom: '오펜시브 킹덤',
}

// for background-color, color
const productType = {
  normal: 'normal',
  light: 'light',
  dark: 'dark',
  fire: 'fire',
  water: 'water',
  tree: 'tree',
  normal_ivory: 'normal_ivory',
}

const group = {
  dingo: 'dingo',
  blackDye: 'blackDye',
  increaseWood: 'increaseWood',
  increaseFire: 'increaseFire',
  light1: 'light1',
  light2: 'light2',
  light3: 'light3',
  dark1: 'dark1',
  dark2: 'dark2',
  dark3: 'dark3',
  fire1: 'fire1',
  fire2: 'fire2',
  fire3: 'fire3',
  water1: 'water1',
  water2: 'water2',
  water3: 'water3',
  tree1: 'tree1',
  tree2: 'tree2',
  tree3: 'tree3',
  throneSkillBook: 'throneSkillBook',
  darkMagicCrystal100: 'darkMagicCrystal100',
  blackRidingDye: 'blackRidingDye',
  ivoryRidingDye: 'ivoryRidingDye',
  defensiveKingdom: 'defensiveKingdom',
  offensiveKingdom: 'offensiveKingdom',
}

const products = [
  {
    name: '유물 전장 승리: 딩고 호박 2개',
    rewards: [reward.dingo, reward.dingo],
    type: productType.normal,
    group: group.dingo,
  },
  {
    name: '유물 전장 승리: 블랙 염색약 2개',
    rewards: [reward.blackDye, reward.blackDye],
    type: productType.normal,
    group: group.blackDye,
  },
  {
    name: '유물 전장 패배: 딩고 호박',
    rewards: [reward.dingo],
    type: productType.normal,
    group: group.dingo,
  },
  {
    name: '엔트 석상 4단계: 인크리스 우드',
    rewards: [reward.increaseWood],
    type: productType.tree,
    group: group.increaseWood,
  },
  {
    name: '엔트 석상 5단계: 인크리스 우드 2권',
    rewards: [reward.increaseWood, reward.increaseWood],
    type: productType.tree,
    group: group.increaseWood,
  },
  {
    name: '엔트 석상 6단계: 인크리스 우드 2권',
    rewards: [reward.increaseWood, reward.increaseWood],
    type: productType.tree,
    group: group.increaseWood,
  },
  {
    name: '화염의 기사 라스 4단계: 인크리스 파이어',
    rewards: [reward.increaseFire],
    type: productType.fire,
    group: group.increaseFire,
  },
  {
    name: '화염의 기사 라스 5단계: 인크리스 파이어 2권',
    rewards: [reward.increaseFire, reward.increaseFire],
    type: productType.fire,
    group: group.increaseFire,
  },
  {
    name: '화염의 기사 라스 6단계: 인크리스 파이어 2권',
    rewards: [reward.increaseFire, reward.increaseFire],
    type: productType.fire,
    group: group.increaseFire,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 빛 스킬북 II',
    rewards: [reward.lightSkillBook2],
    type: productType.light,
    group: group.light2,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 빛 스킬북 III',
    rewards: [reward.lightSkillBook3],
    type: productType.light,
    group: group.light3,
  },
  {
    name: '킹덤 디펜스 5단계 패배: 빛 스킬북 I',
    rewards: [reward.lightSkillBook1],
    type: productType.light,
    group: group.light1,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 어둠 스킬북 II',
    rewards: [reward.darkSkillBook2],
    type: productType.dark,
    group: group.dark2,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 어둠 스킬북 III',
    rewards: [reward.darkSkillBook3],
    type: productType.dark,
    group: group.dark3,
  },
  {
    name: '킹덤 디펜스 5단계 패배: 어둠 스킬북 I',
    rewards: [reward.darkSkillBook1],
    type: productType.dark,
    group: group.dark1,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 불 스킬북 II',
    rewards: [reward.fireSkillBook2],
    type: productType.fire,
    group: group.fire2,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 불 스킬북 III',
    rewards: [reward.fireSkillBook3],
    type: productType.fire,
    group: group.fire3,
  },
  {
    name: '킹덤 디펜스 5단계 패배: 불 스킬북 I',
    rewards: [reward.fireSkillBook1],
    type: productType.fire,
    group: group.fire1,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 물 스킬북 II',
    rewards: [reward.waterSkillBook2],
    type: productType.water,
    group: group.water2,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 물 스킬북 III',
    rewards: [reward.waterSkillBook3],
    type: productType.water,
    group: group.water3,
  },
  {
    name: '킹덤 디펜스 5단계 패배: 물 스킬북 I',
    rewards: [reward.waterSkillBook1],
    type: productType.water,
    group: group.water1,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 나무 스킬북 II',
    rewards: [reward.treeSkillBook2],
    type: productType.tree,
    group: group.tree2,
  },
  {
    name: '킹덤 디펜스 5단계 승리: 나무 스킬북 III',
    rewards: [reward.treeSkillBook3],
    type: productType.tree,
    group: group.tree3,
  },
  {
    name: '킹덤 디펜스 5단계 패배: 나무 스킬북 I',
    rewards: [reward.treeSkillBook1],
    type: productType.tree,
    group: group.tree1,
  },
  {
    name: '왕위 쟁탈전 승리: 왕성 스킬북 상자',
    rewards: [reward.throneSkillBook],
    type: productType.normal,
    group: group.throneSkillBook,
  },
  {
    name: '왕위 쟁탈전 승리: 흑마법 결정 100개 x 2',
    rewards: [reward.darkMagicCrystal100, reward.darkMagicCrystal100],
    type: productType.normal,
    group: group.darkMagicCrystal100,
  },
  {
    name: '왕위 쟁탈전 승리: 블랙 탈 것 염색약 2개',
    rewards: [reward.blackRidingDye, reward.blackRidingDye],
    type: productType.normal,
    group: group.blackRidingDye,
  },
  {
    name: '왕위 쟁탈전 패배: 왕성 스킬북 상자 2권',
    rewards: [reward.throneSkillBook, reward.throneSkillBook],
    type: productType.normal,
    group: group.throneSkillBook,
  },
  {
    name: '왕위 쟁탈전 패배: 흑마법 결정 100개',
    rewards: [reward.darkMagicCrystal100],
    type: productType.normal,
    group: group.darkMagicCrystal100,
  },
  {
    name: '왕위 쟁탈전 패배: 블랙 탈 것 염색약',
    rewards: [reward.blackRidingDye],
    type: productType.normal,
    group: group.blackRidingDye,
  },
  {
    name: '킹덤 침공전 승리: 아이보리 탈 것 염색약 2개',
    rewards: [reward.ivoryRidingDye, reward.ivoryRidingDye],
    type: productType.normal_ivory,
    group: group.ivoryRidingDye,
  },
  {
    name: '킹덤 침공전 패배: 아이보리 탈 것 염색약',
    rewards: [reward.ivoryRidingDye],
    type: productType.normal_ivory,
    group: group.ivoryRidingDye,
  },
  {
    name: '유물 판매 보상: 디펜시브 킹덤',
    rewards: [reward.defensiveKingdom],
    type: productType.normal,
    group: group.defensiveKingdom,
  },
  {
    name: '유물 판매 보상: 오펜시브 킹덤',
    rewards: [reward.offensiveKingdom],
    type: productType.normal,
    group: group.offensiveKingdom,
  },
].map((p, idx) => ({ ...p, id: idx + 1 }))

const members = [
  { name: '단밤' },
  { name: '어머' },
  { name: '워니니' },
  { name: '유한량' },
  { name: 'HyunA' },
  { name: '꼬마짱구' },
  { name: '주녕코' },
  { name: 'ESNA' },
  { name: '르미르르미' },
  { name: '리치푸른' },
  { name: '리망' },
  { name: '김쨩아' },
  { name: '플럼' },
  { name: '능구렁이' },
  { name: '구름빛블루베리' },
  { name: '슈슈베리' },
  { name: '파랑공룡' },
  { name: '쳔상' },
  { name: '규일이' },
  { name: '르릉' },
  { name: 'HOWL하울' },
  { name: '초원의초밥' },
  { name: '명탐정밍또찌' },
  { name: '막힛' },
  { name: '유기농브로콜리' },
  { name: '네츠' },
  { name: '맛깔고등어로버프' },
  { name: '못생긴붕어' },
  { name: '박삐뽀' },
  { name: '세비' },
  { name: '소금맛아이스' },
  { name: '신기하당' },
  { name: '츄베리' },
  { name: '카사리안' },
  { name: '커꾜' },
  { name: '커덩' },
  { name: '포동포포이' },
  { name: '형낑' },
  { name: '김얄루' },
  { name: '김은님' },
  { name: '행복이숑' },
  { name: '밍공이' },
  { name: '폭력군' },
  { name: '복수의망치' },
  { name: '날아라치킨맨' },
  { name: '때리지마라' },
  { name: '쑥덕이' },
  { name: '곰탱아' },
  { name: '희네입니다' },
  { name: '단밤찐빵' },
]
  .sort((a, b) => {
    if (a.name < b.name) {
      return -1
    }
    return 1
  })
  .map((m, idx) => ({
    ...m,
    id: idx + 1,
    stack: 0,
    rewards: [],
  }))
